pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/opt/homebrew/Cellar/maven/3.9.6/libexec/binmvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/opt/homebrew/Cellar/maven/3.9.6/libexec/bin mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('complete'){
            steps{
            echo 'pipeline completed'
            }
        }    
    }
}
